#!/usr/bin/env bun
/**
 * Refresh `src/lib/versions.ts` from the contents of `content/docs/sdk/api/`
 * and `content/docs/sdk/release-notes/`.
 *
 * The site has two versioned sections (API summary, release notes), each
 * served as a single MDX file per version:
 *   - `<basePath>/index.mdx`            — current latest
 *   - `<basePath>/v<X.Y.Z>.mdx`         — older versions
 *
 * This script discovers all `vX.Y.Z.mdx` siblings, sorts them descending,
 * and rewrites `versions.ts` so the version selector dropdowns always
 * reflect what's actually on disk.
 *
 * Usage:
 *   bun run scripts/update-versions-list.ts [--latest=X.Y.Z]
 *
 * The `--latest=X.Y.Z` flag controls the version label rendered as
 * "vX.Y.Z (latest)" — both for the API summary and release notes. If
 * omitted, the script reads the SDK's own `package.json` version.
 */

import * as fs from "fs/promises";
import * as path from "path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const DOCS_WEBSITE_DIR = path.resolve(SCRIPT_DIR, "..");
const SDK_PKG_JSON = path.resolve(
  SCRIPT_DIR,
  "..",
  "..",
  "..",
  "packages",
  "sdk",
  "package.json",
);

function compareSemverDesc(a: string, b: string): number {
  const aVer = a.replace(/^v/, "").split(".").map(Number);
  const bVer = b.replace(/^v/, "").split(".").map(Number);
  for (let i = 0; i < 3; i++) {
    if (aVer[i] !== bVer[i]) return bVer[i] - aVer[i];
  }
  return 0;
}

async function discoverSectionVersions(sectionDir: string): Promise<string[]> {
  let entries;
  try {
    entries = await fs.readdir(sectionDir, { withFileTypes: true });
  } catch {
    return [];
  }
  return entries
    .filter((e) => e.isFile() && e.name.endsWith(".mdx") && e.name !== "index.mdx")
    .map((e) => e.name.replace(/\.mdx$/, ""))
    .filter((name) => /^v\d+\.\d+\.\d+$/.test(name))
    .sort(compareSemverDesc);
}

async function readSdkVersion(): Promise<string> {
  const raw = await fs.readFile(SDK_PKG_JSON, "utf-8");
  const pkg = JSON.parse(raw) as { version?: string };
  if (!pkg.version) {
    throw new Error(`Could not read version from ${SDK_PKG_JSON}`);
  }
  return `v${pkg.version}`;
}

function buildSectionLiteral(
  basePath: string,
  latest: string,
  olderVersions: string[],
): string {
  const lines: string[] = [];
  lines.push(`{`);
  lines.push(`  basePath: '${basePath}',`);
  lines.push(`  latest: '${latest}',`);
  lines.push(`  versions: [`);
  lines.push(
    `    { label: '${latest} (latest)', value: '${latest}', isLatest: true },`,
  );
  for (const v of olderVersions) {
    lines.push(`    { label: '${v}', value: '${v}' },`);
  }
  lines.push(`  ],`);
  lines.push(`}`);
  return lines.join("\n");
}

async function updateVersionsList(latestOverride?: string) {
  console.log(`📋 Updating versions list...`);

  const apiDir = path.join(
    DOCS_WEBSITE_DIR,
    "content",
    "docs",
    "sdk",
    "api",
  );
  const releaseNotesDir = path.join(
    DOCS_WEBSITE_DIR,
    "content",
    "docs",
    "sdk",
    "release-notes",
  );

  const latest = latestOverride
    ? latestOverride.startsWith("v")
      ? latestOverride
      : `v${latestOverride}`
    : await readSdkVersion();
  console.log(`   Latest: ${latest}`);

  const apiOlder = await discoverSectionVersions(apiDir);
  const releaseNotesOlder = await discoverSectionVersions(releaseNotesDir);
  console.log(
    `   API older versions: ${apiOlder.join(", ") || "(none)"}`,
  );
  console.log(
    `   Release notes older versions: ${releaseNotesOlder.join(", ") || "(none)"}`,
  );

  const apiSection = buildSectionLiteral("/sdk/api", latest, apiOlder);
  const releaseNotesSection = buildSectionLiteral(
    "/sdk/release-notes",
    latest,
    releaseNotesOlder,
  );

  const content = `/**
 * Section-scoped version manifest. Only the API summary and the release
 * notes are versioned in the docs site — everything else (about-qvac,
 * getting-started, examples, tutorials, addons, cli, http-server) lives at
 * a single bare path that always reflects the current SDK.
 *
 * Each section is a single content folder under \`content/docs/<basePath>/\`:
 *   - The latest version is served from \`index.mdx\` at the bare basePath.
 *   - Older versions are served from \`<basePath>/v<X.Y.Z>\` via a sibling
 *     MDX file (\`v<X.Y.Z>.mdx\`).
 *
 * Auto-generated by \`scripts/update-versions-list.ts\` — do not edit by
 * hand for routine releases.
 */

export interface VersionEntry {
  label: string;
  value: string;
  isLatest?: boolean;
}

export interface VersionedSection {
  basePath: string;
  latest: string;
  versions: VersionEntry[];
}

export const API_SECTION: VersionedSection = ${apiSection};

export const RELEASE_NOTES_SECTION: VersionedSection = ${releaseNotesSection};

const VERSIONED_SECTIONS: VersionedSection[] = [
  API_SECTION,
  RELEASE_NOTES_SECTION,
];

/**
 * Re-exported for backward compatibility with consumers that advertise the
 * latest SDK version in plain text (e.g. the \`llms.txt\` route).
 */
export const LATEST_VERSION = API_SECTION.latest;

/**
 * Return the versioned section the given pathname falls under, or \`null\`
 * when the pathname is not within any versioned section.
 */
export function getVersionedSection(
  pathname: string,
): VersionedSection | null {
  const normalized = pathname.replace(/\\/+$/, '') || '/';
  return (
    VERSIONED_SECTIONS.find(
      (section) =>
        normalized === section.basePath ||
        normalized.startsWith(section.basePath + '/'),
    ) ?? null
  );
}

/**
 * Extract the current version slug from a versioned-section pathname.
 * Returns \`section.latest\` when on the bare \`basePath\` (\`index.mdx\`).
 */
export function getCurrentVersion(
  pathname: string,
  section: VersionedSection,
): string {
  const tail = pathname
    .slice(section.basePath.length)
    .replace(/^\\/+|\\/+$/g, '');
  if (!tail) return section.latest;
  return tail.split('/')[0];
}

/**
 * Build the URL to navigate to when the user picks a target version inside
 * a section. The latest version maps to the bare \`basePath\`; any other
 * version maps to \`basePath/<value>\`.
 */
export function computeSectionVersionUrl(
  section: VersionedSection,
  targetVersion: string,
): string {
  if (targetVersion === section.latest) return section.basePath;
  return \`\${section.basePath}/\${targetVersion}\`;
}
`;

  const versionsFile = path.join(DOCS_WEBSITE_DIR, "src", "lib", "versions.ts");
  await fs.writeFile(versionsFile, content, "utf-8");
  console.log(`✅ Updated ${versionsFile}`);
}

const args = process.argv.slice(2);

if (args.includes("--help") || args.includes("-h")) {
  console.log("Usage: bun run scripts/update-versions-list.ts [--latest=X.Y.Z]");
  console.log("");
  console.log(
    "  --latest=X.Y.Z  Override which version is marked as latest. Defaults",
  );
  console.log(
    "                  to the SDK package.json version.",
  );
  process.exit(0);
}

const latestFlag = args.find((a) => a.startsWith("--latest="));
const latestOverride = latestFlag?.split("=")[1];

updateVersionsList(latestOverride).catch((error) => {
  console.error("❌ Error updating versions list:", error.message);
  if (error.stack) console.error(error.stack);
  process.exit(1);
});
