import RPC from "bare-rpc";
import type { Duplex, DuplexEvents } from "bare-stream";
import type { Worklet } from "react-native-bare-kit";
import { RPCConnectionFailedError } from "@/utils/errors-client";
import { initializeConfig } from "@/client/init-hooks";
import { resolveConfig } from "@/client/config-loader/resolve-config.expo";
import { getClientLogger } from "@/logging";
import { getDeviceInfo } from "@/client/rpc/expo-device-info";
import type { RuntimeContext } from "@/schemas";

const logger = getClientLogger();

let rpcInstance: RPC | null = null;
let rpcPromise: Promise<RPC> | null = null;
let workletInstance: Worklet | null = null;
let workletInitialized = false;
let cachedRuntimeContext: RuntimeContext | undefined;
// Set while close() is in flight. Concurrent callers share the same
// promise instead of double-sending __shutdown__ or re-entering the
// terminate block on already-null state.
let closingPromise: Promise<void> | null = null;

logger.debug("EXPO RPC Client bundle");

async function getRuntimeContext(): Promise<RuntimeContext> {
  if (cachedRuntimeContext) {
    return cachedRuntimeContext;
  }

  const { platform, deviceModel, deviceBrand } = await getDeviceInfo();

  cachedRuntimeContext = {
    runtime: "react-native",
    platform,
    deviceModel,
    deviceBrand,
  };

  return cachedRuntimeContext;
}

export async function getRPC() {
  if (rpcInstance) {
    return rpcInstance;
  }

  if (rpcPromise) {
    return rpcPromise;
  }

  rpcPromise = (async () => {
    if (workletInstance) {
      logger.debug("🔄 Reusing existing worklet");
      rpcInstance = new RPC(
        workletInstance.IPC as unknown as Duplex<DuplexEvents>,
        () => {},
      );
      // Only initialize once per worklet - server state persists
      if (!workletInitialized) {
        const runtimeContext = await getRuntimeContext();
        await initializeConfig(rpcInstance, resolveConfig, runtimeContext);
        workletInitialized = true;
      }
      return rpcInstance;
    }

    const { Paths } = await import("expo-file-system");
    const bareKitModule = await import("react-native-bare-kit");

    const worklet = new bareKitModule.Worklet();
    workletInstance = worklet;
    logger.debug("Starting new worklet");

    // Load the mobile bundle - generated by expo plugin during prebuild
    // The expo plugin handles bundle selection:
    // 1. Uses qvac/worker.bundle.js if exists (user pre-generated)
    // 2. Generates tree-shaken bundle if qvac.config.* exists
    // 3. Generates default bundle (all plugins) otherwise
    let mobileBundle;
    try {
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      mobileBundle = require("@qvac/sdk/worker.mobile.bundle") as unknown;
    } catch (error) {
      const message =
        "Failed to load mobile worker bundle. Make sure the QVAC Expo plugin is configured. " +
        `Add '@qvac/sdk/expo-plugin' to your app.json plugins array. ` +
        `Error: ${String(error)}`;
      logger.error(message);
      throw new RPCConnectionFailedError(
        message,
        error instanceof Error ? error : undefined,
      );
    }

    worklet.start("worker.bundle", mobileBundle as string, [
      // Normalize arg number across platforms
      "react-native-bare-kit",
      "worker.js",
      JSON.stringify({
        HOME_DIR: Paths.document.uri.replace("file://", ""),
      }),
    ]);
    logger.info("Worklet started");
    rpcInstance = new RPC(
      worklet.IPC as unknown as Duplex<DuplexEvents>,
      () => {
        // Use this for async callbacks
      },
    );

    const runtimeContext = await getRuntimeContext();
    await initializeConfig(rpcInstance, resolveConfig, runtimeContext);
    workletInitialized = true;

    return rpcInstance;
  })();

  try {
    return await rpcPromise;
  } catch (error) {
    logger.error(`Failed to initialize RPC: ${String(error)}`);
    throw error;
  } finally {
    rpcPromise = null;
  }
}

const SHUTDOWN_RPC_TIMEOUT_MS = 10_000;

/**
 * Pre-terminate cleanup roundtrip. Sends an internal `__shutdown__` message
 * to the worker so it can clear addon plugin registries (calls each addon's
 * `releaseLogger` → frees env-bound js_ref_t state) and unload all model
 * instances BEFORE we kill the worklet.
 *
 * Without this, the worklet's V8 isolate dies while addon static state still
 * holds js_ref_t handles into it; the next worklet's first `setLogger` call
 * trips a V8 GlobalHandle assertion (brk 0 / SIGTRAP) and the iOS app dies.
 *
 * Best-effort: never throws. Falls through to terminate even on timeout.
 */
async function sendShutdownMessage(rpc: RPC): Promise<void> {
  let timer: ReturnType<typeof setTimeout> | undefined;
  try {
    await Promise.race([
      (async () => {
        const req = rpc.request(1);
        req.send(JSON.stringify({ type: "__shutdown__" }), "utf8");
        const response = await req.reply("utf8");
        const parsed = JSON.parse(String(response)) as {
          success: boolean;
          error?: string;
        };
        if (!parsed.success) {
          throw new Error(parsed.error ?? "Worker reported cleanup failure");
        }
      })(),
      new Promise<never>((_, reject) => {
        timer = setTimeout(
          () =>
            reject(
              new Error(
                `Worker did not ack __shutdown__ within ${SHUTDOWN_RPC_TIMEOUT_MS}ms`,
              ),
            ),
          SHUTDOWN_RPC_TIMEOUT_MS,
        );
      }),
    ]);
  } catch (error) {
    // Best-effort: log but don't block termination if cleanup fails.
    logger.warn(
      `⚠️ Pre-terminate worker cleanup failed: ${
        error instanceof Error ? error.message : String(error)
      }`,
    );
  } finally {
    if (timer) clearTimeout(timer);
  }
}

export async function close(): Promise<void> {
  // Concurrent callers (or a getRPC retry that overlaps with a manual
  // close) share the in-flight close promise instead of each sending
  // their own __shutdown__ and racing on the terminate block.
  if (closingPromise) return closingPromise;

  closingPromise = (async () => {
    logger.info("🧹 Closing RPC client (Expo)");

    // terminate() crashes on Android (addon dlclose leaves pthread_key_t
    // destructors dangling); iOS dyld no-ops dlclose so it's safe there.
    // Non-iOS: drop refs only -- sending __shutdown__ without a follow-up
    // terminate would clear the worker plugin registry.
    let platform: string | undefined;
    try {
      platform = (await getRuntimeContext()).platform;
    } catch (err) {
      logger.debug("Failed to resolve runtime context for close()", { err });
    }

    if (platform !== "ios") {
      rpcInstance = null;
      rpcPromise = null;
      return;
    }

    // iOS: existing pre-terminate cleanup + terminate.
    if (rpcInstance) {
      logger.info("🧹 Requesting worker pre-terminate cleanup");
      await sendShutdownMessage(rpcInstance);
    }

    rpcInstance = null;
    rpcPromise = null;
    if (workletInstance) {
      logger.info("🐻🔫 Terminating bare worklet");
      try {
        workletInstance.terminate();
      } catch (error) {
        logger.debug("Failed to terminate worklet", { error });
      }
      workletInstance = null;
      workletInitialized = false;
    }
  })();

  try {
    await closingPromise;
  } finally {
    // Reset so a subsequent close() (e.g. after a fresh getRPC spawned
    // a new worklet) can run again. Body guards on rpcInstance / workletInstance
    // make a redundant call a no-op if state is already cleared.
    closingPromise = null;
  }
}

export async function createDuplexSession(payload: string, commandId: number) {
  const rpc = await getRPC();
  const req = rpc.request(commandId);
  const requestStream = req.createRequestStream();
  const responseStream = req.createResponseStream({ encoding: "utf-8" });
  // Pre-encode payload — RN/Hermes lacks a global `Buffer`, so `write(string, "utf-8")` would throw.
  requestStream.write(new TextEncoder().encode(payload));
  return { requestStream, responseStream };
}
