import { generateExportName } from "./naming";
import type { ProcessedModel } from "./types";

export function generateModelsFileContent(models: ProcessedModel[]): string {
  const usedNames = new Set<string>();
  const named = new Map<ProcessedModel, string>();

  const exportable = models.filter((m) => !m.isCompanionOnly);
  const companionOnly = models.filter((m) => m.isCompanionOnly);

  for (const m of exportable) {
    named.set(m, assignName(m, usedNames));
  }
  for (const m of companionOnly) {
    named.set(m, assignName(m, usedNames));
  }

  const modelsWithNames = models.map((m) => ({
    ...m,
    name: named.get(m)!,
  }));

  return generateFileContentWithNames(modelsWithNames);
}

function assignName(m: ProcessedModel, usedNames: Set<string>): string {
  return generateExportName({
    path: m.registryPath,
    engine: m.engine,
    name: m.modelName,
    quantization: m.quantization,
    params: m.params,
    tags: m.tags,
    usedNames,
  });
}

function generateFileContentWithNames(
  modelsWithNames: (ProcessedModel & { name: string })[],
): string {
  const entries = modelsWithNames
    .map((m) => {
      const addonAlias = m.addon;
      let entry = `  {
    name: "${m.name}",
    registryPath: "${m.registryPath}",
    registrySource: "${m.registrySource}",
    blobCoreKey: "${m.blobCoreKey}",
    blobBlockOffset: ${m.blobBlockOffset},
    blobBlockLength: ${m.blobBlockLength},
    blobByteOffset: ${m.blobByteOffset},
    modelId: "${m.modelId}",
    addon: "${addonAlias}",
    expectedSize: ${m.expectedSize},
    sha256Checksum: "${m.sha256Checksum}",
    engine: "${m.engine}",
    quantization: "${m.quantization || ""}",
    params: "${m.params || ""}"`;

      if (m.shardMetadata) {
        entry += `,\n    shardMetadata: ${JSON.stringify(m.shardMetadata)}`;
      }

      if (m.companionSet) {
        entry += `,\n    companionSet: ${JSON.stringify(m.companionSet)}`;
      }

      entry += "\n  }";
      return entry;
    })
    .join(",\n");

  const exports = modelsWithNames
    .filter((m) => !m.isCompanionOnly)
    .map((m) => {
      const i = modelsWithNames.indexOf(m);
      return `export const ${m.name} = {
  name: "${m.name}",
  src: \`registry://\${models[${i}].registrySource}/\${models[${i}].registryPath}\`,
  registryPath: models[${i}].registryPath,
  registrySource: models[${i}].registrySource,
  blobCoreKey: models[${i}].blobCoreKey,
  blobBlockOffset: models[${i}].blobBlockOffset,
  blobBlockLength: models[${i}].blobBlockLength,
  blobByteOffset: models[${i}].blobByteOffset,
  modelId: models[${i}].modelId,
  expectedSize: models[${i}].expectedSize,
  sha256Checksum: models[${i}].sha256Checksum,
  addon: models[${i}].addon,
  engine: models[${i}].engine,
  quantization: models[${i}].quantization,
  params: models[${i}].params,
} as const;`;
    })
    .join("\n\n");

  return `// THIS FILE IS AUTO-GENERATED BY models/update-models
// DO NOT MODIFY MANUALLY

import type {
  ModelRegistryEngine,
  ModelRegistryEntryAddon,
} from "@/schemas/registry";
import type { ENGINE_TO_ADDON } from "@/schemas/engine-addon-map";

type AddonOfEngine<E extends ModelRegistryEngine> = (typeof ENGINE_TO_ADDON)[E];

export type RegistryItem = {
  name: string;
  registryPath: string;
  registrySource: string;
  blobCoreKey: string;
  blobBlockOffset: number;
  blobBlockLength: number;
  blobByteOffset: number;
  modelId: string;
  addon: ModelRegistryEntryAddon;
  expectedSize: number;
  sha256Checksum: string;
  engine: ModelRegistryEngine;
  quantization: string;
  params: string;
  shardMetadata?: readonly {
    filename: string;
    expectedSize: number;
    sha256Checksum: string;
    blobCoreKey: string;
    blobBlockOffset: number;
    blobBlockLength: number;
    blobByteOffset: number;
  }[];
  companionSet?: {
    setKey: string;
    primaryKey: string;
    files: readonly {
      key: string;
      registryPath: string;
      registrySource: string;
      targetName: string;
      expectedSize: number;
      sha256Checksum: string;
      blobCoreKey: string;
      blobBlockOffset: number;
      blobBlockLength: number;
      blobByteOffset: number;
      primary?: boolean;
    }[];
  };
};

/** Generic so callers can preserve per-constant literals: \`ModelConstant<"llamacpp-completion">\`. */
export type ModelConstant<
  TEngine extends ModelRegistryEngine = ModelRegistryEngine,
> = {
  name: string;
  src: string;
  registryPath: string;
  registrySource: string;
  blobCoreKey: string;
  blobBlockOffset: number;
  blobBlockLength: number;
  blobByteOffset: number;
  modelId: string;
  expectedSize: number;
  sha256Checksum: string;
  addon: AddonOfEngine<TEngine>;
  engine: TEngine;
  quantization: string;
  params: string;
};

export const models = [
${entries}
] as const satisfies readonly RegistryItem[];

// Individual model constants for direct import/use with loadModel
// These contain all metadata and can be used directly: loadModel({ modelSrc: WHISPER_TINY, ... })
${exports}

// Helper function to get model by name
export function getModelByName(name: string): RegistryItem | undefined {
  return models.find((model) => model.name === name);
}

// Helper function to get model by registry path
export function getModelByPath(registryPath: string): RegistryItem | undefined {
  return models.find((model) => model.registryPath === registryPath);
}

// Helper function for blob-based lookups
export function getModelBySrc(modelId: string, blobCoreKey: string): RegistryItem | undefined {
  return models.find((model) => model.modelId === modelId && model.blobCoreKey === blobCoreKey);
}
`;
}
