#!/usr/bin/env node

'use strict'

const fs = require('fs')
const path = require('path')
const { REPO_ROOT, PACKAGES_DIR, normalizeLicenseId } = require('./lib/config')
const { COPYRIGHT_HOLDER, COPYRIGHT_YEAR } = require('./constants')
const { collator } = require('./lib/utils')

// ---------------------------------------------------------------------------
// Usage
// ---------------------------------------------------------------------------
function printUsage () {
  console.log(`
Usage: node generate-report.js

Reads existing NOTICE files from all packages and produces a license
overview report at NOTICE_FULL_REPORT.txt in the repo root.

Does NOT scan or modify anything — only reads NOTICE files that were
previously generated by generate-notice.js.

Output:  NOTICE_FULL_REPORT.txt (gitignored)
`)
}

// ---------------------------------------------------------------------------
// Parse a NOTICE file into structured data
// ---------------------------------------------------------------------------
function parseNoticeFile (noticePath) {
  if (!fs.existsSync(noticePath)) return null
  const content = fs.readFileSync(noticePath, 'utf8')
  if (!content.trim()) return null

  const result = { models: [], js: [], python: [], cpp: [] }
  let currentSection = null // 'models' | 'js' | 'python' | 'cpp'
  let currentLicense = null

  for (const line of content.split('\n')) {
    // Detect section headers
    if (line.includes('Third-Party Model Licenses')) { currentSection = 'models'; currentLicense = null; continue }
    if (line.includes('JavaScript Dependencies')) { currentSection = 'js'; currentLicense = null; continue }
    if (line.includes('Python Dependencies')) { currentSection = 'python'; currentLicense = null; continue }
    if (line.includes('C++ Dependencies')) { currentSection = 'cpp'; currentLicense = null; continue }
    if (line.includes('Modification Notice')) { currentSection = null; continue }
    if (line.includes('Required Attribution')) { currentSection = null; continue }
    if (!currentSection) continue

    // Detect license group header: --- license-id (Friendly Name) ---
    const licenseMatch = line.match(/^---\s+(\S+)/)
    if (licenseMatch) {
      currentLicense = licenseMatch[1]
      continue
    }

    // Detect dependency entry (indented, non-empty, not a URL line)
    const entryMatch = line.match(/^\s{2}(\S.+)/)
    if (entryMatch && currentLicense && !line.match(/^\s{4}/)) {
      const name = entryMatch[1].trim()
      result[currentSection].push({ name, license: currentLicense })
    }
  }

  return result
}

// ---------------------------------------------------------------------------
// Find all NOTICE files in the repo
// ---------------------------------------------------------------------------
function findNoticeFiles () {
  const packages = []

  const topLevel = fs.readdirSync(PACKAGES_DIR, { withFileTypes: true })
    .filter(d => d.isDirectory() && d.name !== 'docs')

  for (const dir of topLevel) {
    // Check for sub-packages (registry-server/client, registry-server/shared)
    if (dir.name === 'registry-server') {
      for (const sub of ['client', 'shared']) {
        const subDir = path.join(PACKAGES_DIR, dir.name, sub)
        const noticePath = path.join(subDir, 'NOTICE')
        const pkgJsonPath = path.join(subDir, 'package.json')
        if (fs.existsSync(noticePath) && fs.existsSync(pkgJsonPath)) {
          const pkg = JSON.parse(fs.readFileSync(pkgJsonPath, 'utf8'))
          packages.push({
            dir: `${dir.name}/${sub}`,
            npmName: pkg.name || `${dir.name}/${sub}`,
            noticePath
          })
        }
      }
      continue
    }

    const noticePath = path.join(PACKAGES_DIR, dir.name, 'NOTICE')
    const pkgJsonPath = path.join(PACKAGES_DIR, dir.name, 'package.json')
    if (fs.existsSync(noticePath) && fs.existsSync(pkgJsonPath)) {
      const pkg = JSON.parse(fs.readFileSync(pkgJsonPath, 'utf8'))
      packages.push({
        dir: dir.name,
        npmName: pkg.name || dir.name,
        noticePath
      })
    }
  }

  return packages.sort((a, b) => collator.compare(a.npmName, b.npmName))
}

// ---------------------------------------------------------------------------
// Build the report
// ---------------------------------------------------------------------------
function buildReport (packages) {
  const lines = [
    'QVAC — License Overview Report',
    `Generated: ${new Date().toISOString()}`,
    `Copyright ${COPYRIGHT_YEAR} ${COPYRIGHT_HOLDER}`,
    '',
    'This report is generated from existing NOTICE files across all packages.',
    'Run generate-notice.js first to create/update NOTICE files.',
    ''
  ]

  const SEP = '='.repeat(73)
  const globalCounts = {}
  let globalTotal = 0
  const perPkgData = []

  for (const pkg of packages) {
    const parsed = parseNoticeFile(pkg.noticePath)
    if (!parsed) continue

    const pkgCounts = {}
    const typeCounts = { models: 0, js: 0, python: 0, cpp: 0 }
    let pkgTotal = 0

    for (const type of ['models', 'js', 'python', 'cpp']) {
      for (const dep of parsed[type]) {
        const key = normalizeLicenseId(dep.license)
        pkgCounts[key] = (pkgCounts[key] || 0) + 1
        globalCounts[key] = (globalCounts[key] || 0) + 1
        typeCounts[type]++
        pkgTotal++
        globalTotal++
      }
    }

    if (pkgTotal > 0) {
      perPkgData.push({ pkg, pkgCounts, typeCounts, total: pkgTotal })
    }
  }

  // Global summary
  lines.push(SEP)
  lines.push('License Distribution (all packages, all dependency types)')
  lines.push(SEP)
  lines.push('')
  lines.push(`Packages with dependencies: ${perPkgData.length} / ${packages.length}`)
  lines.push(`Total dependencies: ${globalTotal}`)
  lines.push('')

  const sortedGlobal = Object.entries(globalCounts).sort((a, b) => b[1] - a[1])
  const maxLicLen = Math.max(...sortedGlobal.map(([l]) => l.length), 10)
  const maxCountLen = String(globalTotal).length

  for (const [license, count] of sortedGlobal) {
    const pct = ((count / globalTotal) * 100).toFixed(1).padStart(5)
    lines.push(
      `  ${license.padEnd(maxLicLen)}  ${String(count).padStart(maxCountLen)}  (${pct}%)`
    )
  }
  lines.push('')

  // Per-package breakdown
  lines.push(SEP)
  lines.push('Per-Package Breakdown')
  lines.push(SEP)
  lines.push('')

  for (const { pkg, pkgCounts, typeCounts, total } of perPkgData) {
    lines.push(`--- ${pkg.npmName} (packages/${pkg.dir}) ---`)
    lines.push('')

    const parts = []
    if (typeCounts.models) parts.push(`${typeCounts.models} models`)
    if (typeCounts.js) parts.push(`${typeCounts.js} JS`)
    if (typeCounts.python) parts.push(`${typeCounts.python} Python`)
    if (typeCounts.cpp) parts.push(`${typeCounts.cpp} C++`)
    lines.push(`  Total: ${total} (${parts.join(', ')})`)

    const sortedPkg = Object.entries(pkgCounts).sort((a, b) => b[1] - a[1])
    for (const [license, count] of sortedPkg) {
      lines.push(`    ${license.padEnd(maxLicLen)}  ${count}`)
    }
    lines.push('')
  }

  // Packages with no deps
  const emptyPkgs = packages.filter(
    p => !perPkgData.find(d => d.pkg.dir === p.dir)
  )
  if (emptyPkgs.length > 0) {
    lines.push('--- No third-party dependencies ---')
    lines.push('')
    for (const p of emptyPkgs) {
      lines.push(`  ${p.npmName} (packages/${p.dir})`)
    }
    lines.push('')
  }

  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
function main () {
  const args = process.argv.slice(2)
  if (args.includes('--help') || args.includes('-h')) {
    printUsage()
    process.exit(0)
  }

  const packages = findNoticeFiles()
  console.log(`Found ${packages.length} packages with NOTICE files`)

  const report = buildReport(packages)
  const reportPath = path.join(REPO_ROOT, 'NOTICE_FULL_REPORT.txt')

  fs.writeFileSync(reportPath, report + '\n')
  console.log(`Wrote ${reportPath}`)

  // Also print to stdout
  console.log('')
  console.log(report)
}

main()
