#include "StepDoctrRecognitionGGML.hpp"

#include <algorithm>
#include <array>
#include <cmath>
#include <cstddef>
#include <cstring>
#include <limits>
#include <memory>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

#include <ggml-alloc.h>
#include <ggml-backend.h>
#include <ggml-cpu.h>
#include <ggml.h>
#include <gguf.h>
#include <opencv2/opencv.hpp>

#include "model-interface/easyocr/pipeline/qlog.hpp"

// NOLINTBEGIN(cppcoreguidelines-pro-bounds-pointer-arithmetic,cppcoreguidelines-pro-bounds-constant-array-index,readability-identifier-naming,readability-identifier-length)
// DSP / LSTM / CRNN inner loops use raw pointer arithmetic, single-letter
// math identifiers (x, t, c, h, bn), snake_case to mirror upstream PyTorch
// state-dict paths, and layer-dim magic numbers that are themselves part
// of the model architecture. Bounds-checking, renaming, or "constant-ising"
// these would either change the source diff against upstream or measurably
// regress hot-path CTC decode / LSTM gate compute throughput.

namespace doctr::ggml::pipeline {

// NOLINTNEXTLINE(bugprone-throwing-static-initialization)
const std::string StepDoctrRecognitionGGML::VOCAB =
    "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
    "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~"
    "\xC2\xB0"
    "\xC2\xA3"
    "\xE2\x82\xAC"
    "\xC2\xA5"
    "\xC2\xA2"
    "\xE0\xB8\xBF"
    "\xC3\xA0"
    "\xC3\xA2"
    "\xC3\xA9"
    "\xC3\xA8"
    "\xC3\xAA"
    "\xC3\xAB"
    "\xC3\xAE"
    "\xC3\xAF"
    "\xC3\xB4"
    "\xC3\xB9"
    "\xC3\xBB"
    "\xC3\xBC"
    "\xC3\xA7"
    "\xC3\x80"
    "\xC3\x82"
    "\xC3\x89"
    "\xC3\x88"
    "\xC3\x8A"
    "\xC3\x8B"
    "\xC3\x8E"
    "\xC3\x8F"
    "\xC3\x94"
    "\xC3\x99"
    "\xC3\x9B"
    "\xC3\x9C"
    "\xC3\x87";

namespace {

constexpr int kInputChannels = 3;
constexpr int kFeatureChannels = 576;
constexpr int kSequenceLength = 32;
constexpr int kVocabSize = 127;
constexpr int kLstmHiddenSize = 128;
constexpr int kLstmLayerCount = 2;
constexpr int kLstmDirectionCount = 2;
constexpr int kLstmGateCount = 4;
constexpr float kBatchNormEps = 1e-5F;
constexpr double kPixelMax = 255.0;

// Sizing constants for the three ggml contexts the recognizer allocates.
// `kWeightsCtxTensorOverhead` is the number of tensor headers we reserve for
// uploading the recognizer weight set; `kGraphCtxTensorOverhead` covers the
// nodes generated by `build_crnn_gen2`; `kMaxGraphNodes` is the upper bound
// passed to `ggml_new_graph_custom`. All are deliberately oversized; the
// real model footprint stays well below them.
constexpr int kWeightsCtxTensorOverhead = 2048;
constexpr int kGraphCtxTensorOverhead = 4096;
constexpr int kMaxGraphNodes = 8192;

// NOLINTBEGIN(bugprone-throwing-static-initialization)
// NOLINTNEXTLINE(modernize-use-std-numbers) - dataset-derived RGB normalization
const cv::Scalar DOCTR_RECO_MEAN(0.694, 0.695, 0.693);
const cv::Scalar DOCTR_RECO_STD(0.299, 0.296, 0.301);
// NOLINTEND(bugprone-throwing-static-initialization)

struct BlockConfig {
  int featureIndex;
  int inputChannels;
  int outputChannels;
  int expansionChannels;
  int kernel;
  bool useSe;
  bool useHardswish;
  int strideW;
  int strideH;
};

constexpr std::array<BlockConfig, 11> kBlocks{{
    {.featureIndex = 1,
     .inputChannels = 16,
     .outputChannels = 16,
     .expansionChannels = 16,
     .kernel = 3,
     .useSe = true,
     .useHardswish = false,
     .strideW = 2,
     .strideH = 2},
    {.featureIndex = 2,
     .inputChannels = 16,
     .outputChannels = 24,
     .expansionChannels = 72,
     .kernel = 3,
     .useSe = false,
     .useHardswish = false,
     .strideW = 1,
     .strideH = 2},
    {.featureIndex = 3,
     .inputChannels = 24,
     .outputChannels = 24,
     .expansionChannels = 88,
     .kernel = 3,
     .useSe = false,
     .useHardswish = false,
     .strideW = 1,
     .strideH = 1},
    {.featureIndex = 4,
     .inputChannels = 24,
     .outputChannels = 40,
     .expansionChannels = 96,
     .kernel = 5,
     .useSe = true,
     .useHardswish = true,
     .strideW = 1,
     .strideH = 2},
    {.featureIndex = 5,
     .inputChannels = 40,
     .outputChannels = 40,
     .expansionChannels = 240,
     .kernel = 5,
     .useSe = true,
     .useHardswish = true,
     .strideW = 1,
     .strideH = 1},
    {.featureIndex = 6,
     .inputChannels = 40,
     .outputChannels = 40,
     .expansionChannels = 240,
     .kernel = 5,
     .useSe = true,
     .useHardswish = true,
     .strideW = 1,
     .strideH = 1},
    {.featureIndex = 7,
     .inputChannels = 40,
     .outputChannels = 48,
     .expansionChannels = 120,
     .kernel = 5,
     .useSe = true,
     .useHardswish = true,
     .strideW = 1,
     .strideH = 1},
    {.featureIndex = 8,
     .inputChannels = 48,
     .outputChannels = 48,
     .expansionChannels = 144,
     .kernel = 5,
     .useSe = true,
     .useHardswish = true,
     .strideW = 1,
     .strideH = 1},
    {.featureIndex = 9,
     .inputChannels = 48,
     .outputChannels = 96,
     .expansionChannels = 288,
     .kernel = 5,
     .useSe = true,
     .useHardswish = true,
     .strideW = 1,
     .strideH = 2},
    {.featureIndex = 10,
     .inputChannels = 96,
     .outputChannels = 96,
     .expansionChannels = 576,
     .kernel = 5,
     .useSe = true,
     .useHardswish = true,
     .strideW = 1,
     .strideH = 1},
    {.featureIndex = 11,
     .inputChannels = 96,
     .outputChannels = 96,
     .expansionChannels = 576,
     .kernel = 5,
     .useSe = true,
     .useHardswish = true,
     .strideW = 1,
     .strideH = 1},
}};

// UTF-8 lead-byte masks for parseVocabToChars: a UTF-8 leading byte
// determines the length of the encoded code point by the position of the
// first 0 bit. See https://en.wikipedia.org/wiki/UTF-8#Encoding for the bit
// patterns. These masks isolate that prefix so the test `(c & mask) == val`
// classifies the byte.
constexpr unsigned char kUtf8OneByteMask = 0x80;    // 1000 0000
constexpr unsigned char kUtf8TwoByteMask = 0xE0;    // 1110 0000
constexpr unsigned char kUtf8TwoByteValue = 0xC0;   // 1100 0000
constexpr unsigned char kUtf8ThreeByteMask = 0xF0;  // 1111 0000
constexpr unsigned char kUtf8ThreeByteValue = 0xE0; // 1110 0000
constexpr unsigned char kUtf8FourByteMask = 0xF8;   // 1111 1000
constexpr unsigned char kUtf8FourByteValue = 0xF0;  // 1111 0000

std::vector<std::string> parseVocabToChars(const std::string& vocab) {
  std::vector<std::string> chars;
  size_t i = 0;
  while (i < vocab.size()) {
    int len = 1;
    const auto c = static_cast<unsigned char>(vocab[i]);
    if ((c & kUtf8OneByteMask) == 0) {
      len = 1;
    } else if ((c & kUtf8TwoByteMask) == kUtf8TwoByteValue) {
      len = 2;
    } else if ((c & kUtf8ThreeByteMask) == kUtf8ThreeByteValue) {
      len = 3;
    } else if ((c & kUtf8FourByteMask) == kUtf8FourByteValue) {
      len = 4;
    }
    chars.push_back(vocab.substr(i, static_cast<size_t>(len)));
    i += static_cast<size_t>(len);
  }
  return chars;
}

[[noreturn]] void raise(const std::string& message) {
  throw std::runtime_error("[DoctrRecognitionGGML] " + message);
}

void fp16ToFp32(const void* src, float* out, size_t count) {
  const auto* halfPtr = static_cast<const ggml_fp16_t*>(src);
  for (size_t i = 0; i < count; ++i) {
    out[i] = ggml_fp16_to_fp32(halfPtr[i]);
  }
}

std::vector<float>
tensorToF32(struct ggml_tensor* tensor, const std::string& name) {
  if (tensor == nullptr) {
    raise("missing tensor: " + name);
  }
  const size_t count = ggml_nelements(tensor);
  std::vector<float> out(count);
  if (tensor->type == GGML_TYPE_F32) {
    std::memcpy(out.data(), tensor->data, count * sizeof(float));
  } else if (tensor->type == GGML_TYPE_F16) {
    fp16ToFp32(tensor->data, out.data(), count);
  } else {
    raise(
        "unsupported tensor dtype for " + name + ": " +
        ggml_type_name(tensor->type));
  }
  return out;
}

struct ggml_tensor* cloneRaw(
    // NOLINTNEXTLINE(bugprone-easily-swappable-parameters)
    struct ggml_context* dstCtx, struct ggml_context* srcCtx,
    const std::string& name) {
  struct ggml_tensor* src = ggml_get_tensor(srcCtx, name.c_str());
  if (src == nullptr) {
    raise("missing GGUF tensor: " + name);
  }
  struct ggml_tensor* dst = ggml_new_tensor(
      dstCtx,
      src->type,
      ggml_n_dims(src),
      src->ne); // NOLINT(hicpp-no-array-decay) - ggml struct member is C array
  ggml_set_name(dst, name.c_str());
  return dst;
}

struct ggml_tensor* newF32Tensor(
    struct ggml_context* ctx, const std::string& name, int nDims,
    const int64_t* shape) {
  struct ggml_tensor* tensor =
      ggml_new_tensor(ctx, GGML_TYPE_F32, nDims, shape);
  ggml_set_name(tensor, name.c_str());
  return tensor;
}

struct ggml_tensor* newF16TensorLike(
    struct ggml_context* ctx, struct ggml_tensor* src,
    const std::string& name) {
  struct ggml_tensor* tensor = ggml_new_tensor(
      ctx,
      GGML_TYPE_F16,
      ggml_n_dims(src),
      src->ne); // NOLINT(hicpp-no-array-decay) - ggml struct member is C array
  ggml_set_name(tensor, name.c_str());
  return tensor;
}

int samePadding(int kernel) { return (kernel - 1) / 2; }

float sigmoid(float value) { return 1.0F / (1.0F + std::exp(-value)); }

struct LstmWeights {
  std::vector<float> weightIh;
  std::vector<float> weightHh;
  std::vector<float> biasIh;
  std::vector<float> biasHh;
  int inputSize{};
};

struct GraphResources {
  std::unique_ptr<struct ggml_context, decltype(&ggml_free)> weightsCtx{
      nullptr, ggml_free};
  std::unique_ptr<struct ggml_context, decltype(&ggml_free)> graphCtx{
      nullptr, ggml_free};
  std::unordered_map<std::string, struct ggml_tensor*> weights;
  ggml_backend_t backend = nullptr;
  ggml_backend_buffer_t weightsBuffer = nullptr;
  ggml_backend_buffer_t graphBuffer = nullptr;
  struct ggml_cgraph* graph = nullptr;
  struct ggml_tensor* input = nullptr;
  struct ggml_tensor* features = nullptr;

  GraphResources() = default;
  ~GraphResources() { reset(); }
  GraphResources(const GraphResources&) = delete;
  GraphResources& operator=(const GraphResources&) = delete;
  GraphResources(GraphResources&&) = delete;
  GraphResources& operator=(GraphResources&&) = delete;

  void reset() {
    graph = nullptr;
    input = nullptr;
    features = nullptr;
    graphCtx.reset();
    if (graphBuffer != nullptr) {
      ggml_backend_buffer_free(graphBuffer);
      graphBuffer = nullptr;
    }
    weights.clear();
    weightsCtx.reset();
    if (weightsBuffer != nullptr) {
      ggml_backend_buffer_free(weightsBuffer);
      weightsBuffer = nullptr;
    }
    if (backend != nullptr) {
      ggml_backend_free(backend);
      backend = nullptr;
    }
  }
};

struct GraphBuilder {
  struct ggml_context* ctx;
  // GraphBuilder is a stateless one-shot helper that never outlives its
  // caller; storing the weight map by reference avoids a deep copy on every
  // graph build.
  // NOLINTNEXTLINE(cppcoreguidelines-avoid-const-or-ref-data-members)
  const std::unordered_map<std::string, struct ggml_tensor*>& w;

  [[nodiscard]] struct ggml_tensor* t(const std::string& name) const {
    auto it = w.find(name);
    if (it == w.end()) {
      raise("missing graph tensor: " + name);
    }
    return it->second;
  }

  struct ggml_tensor* activate(struct ggml_tensor* x, bool useHardswish) const {
    return useHardswish ? ggml_hardswish(ctx, x) : ggml_relu(ctx, x);
  }

  struct ggml_tensor*
  applyBn(struct ggml_tensor* x, const std::string& bnPrefix) const {
    struct ggml_tensor* scaled = ggml_mul(ctx, x, t(bnPrefix + ".scale"));
    return ggml_add(ctx, scaled, t(bnPrefix + ".shift"));
  }

  struct ggml_tensor* convBnAct(
      struct ggml_tensor* x,
      // NOLINTNEXTLINE(bugprone-easily-swappable-parameters)
      const std::string& convPrefix, const std::string& bnPrefix, int strideW,
      int strideH, int kernel, bool applyActivation, bool useHardswish) const {
    struct ggml_tensor* conv = ggml_conv_2d(
        ctx,
        t(convPrefix + ".weight"),
        x,
        strideW,
        strideH,
        samePadding(kernel),
        samePadding(kernel),
        1,
        1);
    conv = applyBn(conv, bnPrefix);
    return applyActivation ? activate(conv, useHardswish) : conv;
  }

  struct ggml_tensor* dwConvBnAct(
      struct ggml_tensor* x,
      // NOLINTNEXTLINE(bugprone-easily-swappable-parameters)
      const std::string& convPrefix, const std::string& bnPrefix, int strideW,
      int strideH, int kernel, bool useHardswish) const {
    struct ggml_tensor* conv = ggml_conv_2d_dw(
        ctx,
        t(convPrefix + ".weight"),
        x,
        strideW,
        strideH,
        samePadding(kernel),
        samePadding(kernel),
        1,
        1);
    conv = applyBn(conv, bnPrefix);
    return activate(conv, useHardswish);
  }

  struct ggml_tensor* convBiasAct(
      struct ggml_tensor* x, const std::string& convPrefix,
      bool applyActivation, bool useHardswish) const {
    struct ggml_tensor* conv =
        ggml_conv_2d(ctx, t(convPrefix + ".weight"), x, 1, 1, 0, 0, 1, 1);
    conv = ggml_add(ctx, conv, t(convPrefix + ".bias_br"));
    return applyActivation ? activate(conv, useHardswish) : conv;
  }

  struct ggml_tensor*
  seBlock(struct ggml_tensor* x, const std::string& sePrefix) const {
    struct ggml_tensor* pooled = ggml_pool_2d(
        ctx,
        x,
        GGML_OP_POOL_AVG,
        static_cast<int>(x->ne[0]),
        static_cast<int>(x->ne[1]),
        static_cast<int>(x->ne[0]),
        static_cast<int>(x->ne[1]),
        0,
        0);
    struct ggml_tensor* fc1 =
        convBiasAct(pooled, sePrefix + ".fc1", true, false);
    struct ggml_tensor* fc2 = convBiasAct(fc1, sePrefix + ".fc2", false, false);
    return ggml_mul(ctx, x, ggml_hardsigmoid(ctx, fc2));
  }

  struct ggml_tensor*
  invertedResidual(struct ggml_tensor* x, const BlockConfig& cfg) const {
    const std::string base =
        "crnn.features." + std::to_string(cfg.featureIndex);
    const bool hasExpand = cfg.expansionChannels != cfg.inputChannels;
    int dwBlockIdx = 0;
    int seBlockIdx = -1;
    int projBlockIdx = 0;

    struct ggml_tensor* y = x;
    if (hasExpand) {
      y = convBnAct(
          y,
          base + ".block.0.0",
          base + ".block.0.1",
          1,
          1,
          1,
          true,
          cfg.useHardswish);
      dwBlockIdx = 1;
      if (cfg.useSe) {
        seBlockIdx = 2;
        projBlockIdx = 3;
      } else {
        projBlockIdx = 2;
      }
    } else if (cfg.useSe) {
      seBlockIdx = 1;
      projBlockIdx = 2;
    } else {
      projBlockIdx = 1;
    }

    const std::string dwBase = base + ".block." + std::to_string(dwBlockIdx);
    y = dwConvBnAct(
        y,
        dwBase + ".0",
        dwBase + ".1",
        cfg.strideW,
        cfg.strideH,
        cfg.kernel,
        cfg.useHardswish);

    if (cfg.useSe) {
      y = seBlock(y, base + ".block." + std::to_string(seBlockIdx));
    }

    const std::string projBase =
        base + ".block." + std::to_string(projBlockIdx);
    y = convBnAct(
        y, projBase + ".0", projBase + ".1", 1, 1, 1, false, cfg.useHardswish);

    if (cfg.strideW == 1 && cfg.strideH == 1 &&
        cfg.inputChannels == cfg.outputChannels) {
      y = ggml_add(ctx, y, x);
    }
    return y;
  }
};

} // namespace

struct StepDoctrRecognitionGGML::Impl {
  GraphResources graph;
  std::array<std::array<LstmWeights, kLstmDirectionCount>, kLstmLayerCount>
      lstm{};
  std::vector<float> linearWeight;
  std::vector<float> linearBias;

  explicit Impl(const std::string& pathRecognizer) { load(pathRecognizer); }

  void load(const std::string& pathRecognizer) {
    graph.reset();
    ggml_backend_dev_t cpuDev =
        ggml_backend_dev_by_type(GGML_BACKEND_DEVICE_TYPE_CPU);
    graph.backend = cpuDev ? ggml_backend_dev_init(cpuDev, nullptr) : nullptr;
    if (graph.backend == nullptr) {
      raise("failed to initialize ggml CPU backend");
    }

    struct ggml_context* ggufGgmlCtx = nullptr;
    gguf_init_params params{.no_alloc = false, .ctx = &ggufGgmlCtx};
    gguf_context* gguf = gguf_init_from_file(pathRecognizer.c_str(), params);
    if (gguf == nullptr) {
      raise("failed to open GGUF file: " + pathRecognizer);
    }
    std::unique_ptr<gguf_context, decltype(&gguf_free)> ggufGuard(
        gguf, gguf_free);
    std::unique_ptr<struct ggml_context, decltype(&ggml_free)> srcCtx(
        ggufGgmlCtx, ggml_free);

    loadGraphWeights(srcCtx.get());
    loadRecurrentWeights(srcCtx.get());
    buildGraph();
  }

  [[nodiscard]] std::vector<float>
  runFeatureExtractor(const std::vector<float>& inputWhcn) const {
    ggml_backend_tensor_set(
        graph.input, inputWhcn.data(), 0, inputWhcn.size() * sizeof(float));

    const ggml_status status =
        ggml_backend_graph_compute(graph.backend, graph.graph);
    if (status != GGML_STATUS_SUCCESS) {
      raise(
          "ggml backend graph compute failed with status " +
          std::to_string(static_cast<int>(status)));
    }

    std::vector<float> features(
        static_cast<size_t>(ggml_nelements(graph.features)));
    ggml_backend_tensor_get(
        graph.features, features.data(), 0, features.size() * sizeof(float));
    return features;
  }

  [[nodiscard]] std::vector<float>
  runLstmLinear(const std::vector<float>& featureWhcn) const {
    std::vector<float> layerInput(
        static_cast<size_t>(kSequenceLength) * kFeatureChannels);
    for (int t = 0; t < kSequenceLength; ++t) {
      for (int c = 0; c < kFeatureChannels; ++c) {
        layerInput[(static_cast<size_t>(t) * kFeatureChannels) + c] =
            featureWhcn[t + (static_cast<size_t>(kSequenceLength) * c)];
      }
    }

    std::vector<float> layerOutput;
    for (int layer = 0; layer < kLstmLayerCount; ++layer) {
      const int inputSize = (layer == 0)
                                ? kFeatureChannels
                                : kLstmHiddenSize * kLstmDirectionCount;
      layerOutput.assign(
          static_cast<size_t>(kSequenceLength) * kLstmHiddenSize *
              kLstmDirectionCount,
          0.0F);
      runLstmDirection(
          layerInput, layerOutput, lstm[layer][0], inputSize, false);
      runLstmDirection(
          layerInput, layerOutput, lstm[layer][1], inputSize, true);
      layerInput.swap(layerOutput);
    }

    std::vector<float> logits(
        static_cast<size_t>(kSequenceLength) * kVocabSize);
    constexpr int finalFeatureSize = kLstmHiddenSize * kLstmDirectionCount;
    for (int t = 0; t < kSequenceLength; ++t) {
      const float* x =
          layerInput.data() + (static_cast<size_t>(t) * finalFeatureSize);
      for (int cls = 0; cls < kVocabSize; ++cls) {
        float value = linearBias[static_cast<size_t>(cls)];
        const float* w =
            linearWeight.data() + (static_cast<size_t>(cls) * finalFeatureSize);
        for (int i = 0; i < finalFeatureSize; ++i) {
          value += w[i] * x[i];
        }
        logits[(static_cast<size_t>(t) * kVocabSize) + cls] = value;
      }
    }
    return logits;
  }

private:
  static void runLstmDirection(
      const std::vector<float>& input, std::vector<float>& output,
      const LstmWeights& weights, int inputSize, bool reverse) {
    std::vector<float> hidden(kLstmHiddenSize, 0.0F);
    std::vector<float> cell(kLstmHiddenSize, 0.0F);
    std::array<float, static_cast<size_t>(kLstmGateCount) * kLstmHiddenSize>
        gates{};

    for (int step = 0; step < kSequenceLength; ++step) {
      const int t = reverse ? (kSequenceLength - 1 - step) : step;
      const float* x = input.data() + (static_cast<size_t>(t) * inputSize);

      for (int gate = 0; gate < kLstmGateCount * kLstmHiddenSize; ++gate) {
        float value = weights.biasIh[static_cast<size_t>(gate)] +
                      weights.biasHh[static_cast<size_t>(gate)];
        const float* wIh =
            weights.weightIh.data() + (static_cast<size_t>(gate) * inputSize);
        for (int i = 0; i < inputSize; ++i) {
          value += wIh[i] * x[i];
        }
        const float* wHh = weights.weightHh.data() +
                           (static_cast<size_t>(gate) * kLstmHiddenSize);
        for (int i = 0; i < kLstmHiddenSize; ++i) {
          value += wHh[i] * hidden[static_cast<size_t>(i)];
        }
        gates[static_cast<size_t>(gate)] = value;
      }

      for (int i = 0; i < kLstmHiddenSize; ++i) {
        const float inputGate = sigmoid(gates[static_cast<size_t>(i)]);
        const float forgetGate =
            sigmoid(gates[kLstmHiddenSize + static_cast<size_t>(i)]);
        const float cellGate =
            std::tanh(gates[(static_cast<size_t>(2) * kLstmHiddenSize) + i]);
        const float outputGate =
            sigmoid(gates[(static_cast<size_t>(3) * kLstmHiddenSize) + i]);
        cell[static_cast<size_t>(i)] =
            (forgetGate * cell[static_cast<size_t>(i)]) +
            (inputGate * cellGate);
        hidden[static_cast<size_t>(i)] =
            outputGate * std::tanh(cell[static_cast<size_t>(i)]);
      }

      const int directionOffset = reverse ? kLstmHiddenSize : 0;
      float* out =
          output.data() +
          static_cast<size_t>(
              (t * kLstmHiddenSize * kLstmDirectionCount) + directionOffset);
      std::memcpy(out, hidden.data(), kLstmHiddenSize * sizeof(float));
    }
  }

  // NOLINTNEXTLINE(readability-function-cognitive-complexity)
  void loadGraphWeights(struct ggml_context* srcCtx) {
    graph.weightsCtx =
        std::unique_ptr<struct ggml_context, decltype(&ggml_free)>(
            ggml_init(
                {.mem_size = ggml_tensor_overhead() * kWeightsCtxTensorOverhead,
                 .mem_buffer = nullptr,
                 .no_alloc = true}),
            ggml_free);
    if (!graph.weightsCtx) {
      raise("failed to allocate GGML weights context");
    }

    auto addRaw = [&](const std::string& name) {
      struct ggml_tensor* dst = cloneRaw(graph.weightsCtx.get(), srcCtx, name);
      graph.weights.emplace(name, dst);
      return dst;
    };

    auto addConvWeight = [&](const std::string& name) {
      struct ggml_tensor* src = ggml_get_tensor(srcCtx, name.c_str());
      if (src == nullptr) {
        raise("missing GGUF tensor: " + name);
      }
      struct ggml_tensor* dst =
          newF16TensorLike(graph.weightsCtx.get(), src, name);
      graph.weights.emplace(name, dst);
      return dst;
    };

    auto addBiasBroadcast = [&](const std::string& name) {
      const std::vector<float> values =
          tensorToF32(ggml_get_tensor(srcCtx, name.c_str()), name);
      const std::array<int64_t, 4> shape = {
          1, 1, static_cast<int64_t>(values.size()), 1};
      graph.weights.emplace(
          name + "_br",
          newF32Tensor(graph.weightsCtx.get(), name + "_br", 4, shape.data()));
    };

    auto addBnAffine = [&](const std::string& prefix) {
      const std::vector<float> weight = tensorToF32(
          ggml_get_tensor(srcCtx, (prefix + ".weight").c_str()),
          prefix + ".weight");
      const std::vector<float> bias = tensorToF32(
          ggml_get_tensor(srcCtx, (prefix + ".bias").c_str()),
          prefix + ".bias");
      const std::vector<float> mean = tensorToF32(
          ggml_get_tensor(srcCtx, (prefix + ".running_mean").c_str()),
          prefix + ".running_mean");
      const std::vector<float> var = tensorToF32(
          ggml_get_tensor(srcCtx, (prefix + ".running_var").c_str()),
          prefix + ".running_var");
      if (weight.size() != bias.size() || weight.size() != mean.size() ||
          weight.size() != var.size()) {
        raise("BatchNorm tensor size mismatch for " + prefix);
      }
      const std::array<int64_t, 4> shape = {
          1, 1, static_cast<int64_t>(weight.size()), 1};
      graph.weights.emplace(
          prefix + ".scale",
          newF32Tensor(
              graph.weightsCtx.get(), prefix + ".scale", 4, shape.data()));
      graph.weights.emplace(
          prefix + ".shift",
          newF32Tensor(
              graph.weightsCtx.get(), prefix + ".shift", 4, shape.data()));
    };

    auto addConvBn = [&](const std::string& convPrefix,
                         const std::string& bnPrefix) {
      addConvWeight(convPrefix + ".weight");
      addBnAffine(bnPrefix);
    };

    auto addConvBias = [&](const std::string& convPrefix) {
      addConvWeight(convPrefix + ".weight");
      addRaw(convPrefix + ".bias");
      addBiasBroadcast(convPrefix + ".bias");
    };

    addConvBn("crnn.features.0.0", "crnn.features.0.1");
    for (const BlockConfig& cfg : kBlocks) {
      const std::string base =
          "crnn.features." + std::to_string(cfg.featureIndex);
      const bool hasExpand = cfg.expansionChannels != cfg.inputChannels;
      int dwBlockIdx = 0;
      int seBlockIdx = -1;
      int projBlockIdx = 0;
      if (hasExpand) {
        addConvBn(base + ".block.0.0", base + ".block.0.1");
        dwBlockIdx = 1;
        if (cfg.useSe) {
          seBlockIdx = 2;
          projBlockIdx = 3;
        } else {
          projBlockIdx = 2;
        }
      } else if (cfg.useSe) {
        seBlockIdx = 1;
        projBlockIdx = 2;
      } else {
        projBlockIdx = 1;
      }

      const std::string dwBase = base + ".block." + std::to_string(dwBlockIdx);
      addConvBn(dwBase + ".0", dwBase + ".1");
      if (cfg.useSe) {
        const std::string seBase =
            base + ".block." + std::to_string(seBlockIdx);
        addConvBias(seBase + ".fc1");
        addConvBias(seBase + ".fc2");
      }
      const std::string projBase =
          base + ".block." + std::to_string(projBlockIdx);
      addConvBn(projBase + ".0", projBase + ".1");
    }
    addConvBn("crnn.features.12.0", "crnn.features.12.1");

    graph.weightsBuffer =
        ggml_backend_alloc_ctx_tensors(graph.weightsCtx.get(), graph.backend);
    if (graph.weightsBuffer == nullptr) {
      raise("failed to allocate GGML weight buffer");
    }
    ggml_backend_buffer_set_usage(
        graph.weightsBuffer, GGML_BACKEND_BUFFER_USAGE_WEIGHTS);

    for (const auto& [name, dst] : graph.weights) {
      if (name.ends_with(".scale") || name.ends_with(".shift") ||
          name.ends_with("_br")) {
        continue;
      }
      struct ggml_tensor* src = ggml_get_tensor(srcCtx, name.c_str());
      if (src == nullptr) {
        raise("source tensor missing while uploading: " + name);
      }
      if (dst->type == src->type) {
        ggml_backend_tensor_set(dst, src->data, 0, ggml_nbytes(src));
      } else if (dst->type == GGML_TYPE_F16 && src->type == GGML_TYPE_F32) {
        const size_t count = ggml_nelements(src);
        std::vector<ggml_fp16_t> values(count);
        ggml_fp32_to_fp16_row(
            static_cast<const float*>(src->data),
            values.data(),
            static_cast<int64_t>(count));
        ggml_backend_tensor_set(
            dst, values.data(), 0, values.size() * sizeof(ggml_fp16_t));
      } else {
        raise("unsupported tensor dtype conversion while uploading: " + name);
      }
    }

    for (const auto& [name, dst] : graph.weights) {
      if (!name.ends_with("_br")) {
        continue;
      }
      const std::string srcName =
          name.substr(0, name.size() - std::string("_br").size());
      const std::vector<float> values =
          tensorToF32(ggml_get_tensor(srcCtx, srcName.c_str()), srcName);
      ggml_backend_tensor_set(
          dst, values.data(), 0, values.size() * sizeof(float));
    }

    for (const auto& [name, dst] : graph.weights) {
      if (!name.ends_with(".scale")) {
        continue;
      }
      const std::string prefix =
          name.substr(0, name.size() - std::string(".scale").size());
      const std::vector<float> weight = tensorToF32(
          ggml_get_tensor(srcCtx, (prefix + ".weight").c_str()),
          prefix + ".weight");
      const std::vector<float> var = tensorToF32(
          ggml_get_tensor(srcCtx, (prefix + ".running_var").c_str()),
          prefix + ".running_var");
      std::vector<float> scale(weight.size());
      for (size_t i = 0; i < weight.size(); ++i) {
        scale[i] = weight[i] / std::sqrt(var[i] + kBatchNormEps);
      }
      ggml_backend_tensor_set(
          dst, scale.data(), 0, scale.size() * sizeof(float));
    }

    for (const auto& [name, dst] : graph.weights) {
      if (!name.ends_with(".shift")) {
        continue;
      }
      const std::string prefix =
          name.substr(0, name.size() - std::string(".shift").size());
      const std::vector<float> bias = tensorToF32(
          ggml_get_tensor(srcCtx, (prefix + ".bias").c_str()),
          prefix + ".bias");
      const std::vector<float> mean = tensorToF32(
          ggml_get_tensor(srcCtx, (prefix + ".running_mean").c_str()),
          prefix + ".running_mean");
      const std::vector<float> weight = tensorToF32(
          ggml_get_tensor(srcCtx, (prefix + ".weight").c_str()),
          prefix + ".weight");
      const std::vector<float> var = tensorToF32(
          ggml_get_tensor(srcCtx, (prefix + ".running_var").c_str()),
          prefix + ".running_var");
      std::vector<float> shift(bias.size());
      for (size_t i = 0; i < bias.size(); ++i) {
        const float scale = weight[i] / std::sqrt(var[i] + kBatchNormEps);
        shift[i] = bias[i] - (mean[i] * scale);
      }
      ggml_backend_tensor_set(
          dst, shift.data(), 0, shift.size() * sizeof(float));
    }
  }

  void loadRecurrentWeights(struct ggml_context* srcCtx) {
    auto loadTensor = [&](const std::string& name) {
      return tensorToF32(ggml_get_tensor(srcCtx, name.c_str()), name);
    };

    for (int layer = 0; layer < kLstmLayerCount; ++layer) {
      for (int direction = 0; direction < kLstmDirectionCount; ++direction) {
        const std::string suffix = direction == 0 ? "" : "_reverse";
        const std::string base = "crnn.decoder.";
        LstmWeights& dst =
            lstm[static_cast<size_t>(layer)][static_cast<size_t>(direction)];
        const std::string layerStr = std::to_string(layer);
        std::string weightIhPath = base;
        weightIhPath.append("weight_ih_l").append(layerStr).append(suffix);
        std::string weightHhPath = base;
        weightHhPath.append("weight_hh_l").append(layerStr).append(suffix);
        std::string biasIhPath = base;
        biasIhPath.append("bias_ih_l").append(layerStr).append(suffix);
        std::string biasHhPath = base;
        biasHhPath.append("bias_hh_l").append(layerStr).append(suffix);
        dst.weightIh = loadTensor(weightIhPath);
        dst.weightHh = loadTensor(weightHhPath);
        dst.biasIh = loadTensor(biasIhPath);
        dst.biasHh = loadTensor(biasHhPath);
        dst.inputSize = layer == 0 ? kFeatureChannels
                                   : kLstmHiddenSize * kLstmDirectionCount;
      }
    }
    linearWeight = loadTensor("crnn.linear.weight");
    linearBias = loadTensor("crnn.linear.bias");
  }

  void buildGraph() {
    graph.graphCtx = std::unique_ptr<struct ggml_context, decltype(&ggml_free)>(
        ggml_init(
            {.mem_size = (ggml_tensor_overhead() * kGraphCtxTensorOverhead) +
                         ggml_graph_overhead(),
             .mem_buffer = nullptr,
             .no_alloc = true}),
        ggml_free);
    if (!graph.graphCtx) {
      raise("failed to allocate GGML graph context");
    }

    struct ggml_context* ctx = graph.graphCtx.get();
    graph.input = ggml_new_tensor_4d(
        ctx, GGML_TYPE_F32, RECOG_WIDTH, RECOG_HEIGHT, kInputChannels, 1);
    ggml_set_name(graph.input, "recognition_input");
    ggml_set_input(graph.input);

    GraphBuilder gb{.ctx = ctx, .w = graph.weights};
    struct ggml_tensor* x = gb.convBnAct(
        graph.input,
        "crnn.features.0.0",
        "crnn.features.0.1",
        2,
        2,
        3,
        true,
        true);
    for (const BlockConfig& cfg : kBlocks) {
      x = gb.invertedResidual(x, cfg);
    }
    x = gb.convBnAct(
        x, "crnn.features.12.0", "crnn.features.12.1", 1, 1, 1, true, true);
    graph.features = x;
    ggml_set_name(graph.features, "crnn_features");
    ggml_set_output(graph.features);

    graph.graph = ggml_new_graph_custom(ctx, kMaxGraphNodes, /*grads=*/false);
    ggml_build_forward_expand(graph.graph, graph.features);

    graph.graphBuffer =
        ggml_backend_alloc_ctx_tensors(graph.graphCtx.get(), graph.backend);
    if (graph.graphBuffer == nullptr) {
      raise("failed to allocate GGML recognition graph buffer");
    }
  }
};

StepDoctrRecognitionGGML::StepDoctrRecognitionGGML(
    const std::string& pathRecognizer, int batchSize, DecodingMethod decoding)
    : impl_(std::make_unique<Impl>(pathRecognizer)), batchSize_(batchSize),
      decodingMethod_(decoding), vocabChars_(parseVocabToChars(VOCAB)) {
  const std::string decodingStr =
      (decoding == DecodingMethod::CTC) ? "CTC" : "ATTENTION";
  QLOG(
      qvac_lib_inference_addon_cpp::logger::Priority::INFO,
      "[DoctrRecognitionGGML] GGML CPU recognizer loaded, batchSize=" +
          std::to_string(batchSize) + ", decoding=" + decodingStr);
  ALOG_INFO(std::string(
      "[DoctrRecognitionGGML] GGML CPU recognizer loaded, decoding=" +
      decodingStr));
}

StepDoctrRecognitionGGML::~StepDoctrRecognitionGGML() = default;

cv::Mat StepDoctrRecognitionGGML::preprocessCrop(
    const cv::Mat& origImg, const std::array<cv::Point2f, 4>& polygon) {
  cv::Mat crop = fourPointTransform(origImg, polygon);
  if (crop.empty() || crop.cols == 0 || crop.rows == 0) {
    return cv::Mat::zeros(RECOG_HEIGHT, RECOG_WIDTH, CV_32FC3);
  }

  const int cropH = crop.rows;
  const int cropW = crop.cols;
  const float scaleH =
      static_cast<float>(RECOG_HEIGHT) / static_cast<float>(cropH);
  const float scaleW =
      static_cast<float>(RECOG_WIDTH) / static_cast<float>(cropW);
  const float cropScale = std::min(scaleH, scaleW);
  const int newH =
      std::max(1, static_cast<int>(static_cast<float>(cropH) * cropScale));
  const int newW =
      std::max(1, static_cast<int>(static_cast<float>(cropW) * cropScale));

  cv::Mat resized;
  cv::resize(crop, resized, cv::Size(newW, newH), 0, 0, cv::INTER_LINEAR);

  cv::Mat padded = cv::Mat::zeros(RECOG_HEIGHT, RECOG_WIDTH, resized.type());
  cv::Mat roi = padded(cv::Rect(0, 0, newW, newH));
  resized.copyTo(roi);

  cv::Mat floatImg;
  padded.convertTo(floatImg, CV_32FC3, 1.0 / kPixelMax);
  cv::subtract(floatImg, DOCTR_RECO_MEAN, floatImg);
  cv::divide(floatImg, DOCTR_RECO_STD, floatImg);
  return floatImg;
}

cv::Mat StepDoctrRecognitionGGML::runSingleInference(const cv::Mat& image) {
  CV_Assert(image.rows == RECOG_HEIGHT && image.cols == RECOG_WIDTH);
  CV_Assert(image.channels() == kInputChannels);
  const size_t planeFloats =
      static_cast<size_t>(RECOG_WIDTH) * RECOG_HEIGHT;
  inputBuffer_.assign(planeFloats * kInputChannels, 0.0F);

  std::vector<cv::Mat> channels;
  cv::split(image, channels);
  CV_Assert(static_cast<int>(channels.size()) == kInputChannels);
  for (int c = 0; c < kInputChannels; ++c) {
    CV_Assert(channels[c].isContinuous() && channels[c].type() == CV_32F);
    std::memcpy(
        inputBuffer_.data() + (planeFloats * static_cast<size_t>(c)),
        channels[c].ptr<float>(),
        planeFloats * sizeof(float));
  }

  std::vector<float> features = impl_->runFeatureExtractor(inputBuffer_);
  logitsBuffer_ = impl_->runLstmLinear(features);

  const std::array<int, 3> sizes = {1, kSequenceLength, kVocabSize};
  return cv::Mat(3, sizes.data(), CV_32F, logitsBuffer_.data()).clone();
}

StepDoctrRecognitionGGML::SoftmaxResult StepDoctrRecognitionGGML::softmaxArgmax(
    // NOLINTNEXTLINE(bugprone-easily-swappable-parameters)
    const cv::Mat& preds, int batchIdx, int timestep, int vocabSize) {
  const size_t batchStride = preds.step[0] / sizeof(float);
  const size_t seqStride = preds.step[1] / sizeof(float);
  const float* row =
      preds.ptr<float>() + (batchIdx * batchStride) + (timestep * seqStride);

  float maxVal = -std::numeric_limits<float>::infinity();
  for (int v = 0; v < vocabSize; v++) {
    maxVal = std::max(maxVal, row[v]);
  }

  float sumExp = 0.0F;
  int bestIdx = 0;
  float bestExp = 0.0F;
  for (int v = 0; v < vocabSize; v++) {
    const float expVal = std::exp(row[v] - maxVal);
    sumExp += expVal;
    if (expVal > bestExp) {
      bestExp = expVal;
      bestIdx = v;
    }
  }
  return {.bestIdx = bestIdx, .bestProb = bestExp / sumExp};
}

std::pair<std::string, float>
StepDoctrRecognitionGGML::decodeAttention(const cv::Mat& preds, int batchIdx) {
  const int seqLen = preds.size[1];
  const int vocabSize = preds.size[2];
  std::string decodedText;
  float confidenceSum = 0.0F;
  int numChars = 0;

  for (int t = 0; t < seqLen; t++) {
    auto [bestIdx, bestProb] = softmaxArgmax(preds, batchIdx, t, vocabSize);
    if (bestIdx >= SPECIAL_TOKEN_IDX) {
      break;
    }
    if (bestIdx >= 0 && std::cmp_less(bestIdx, vocabChars_.size())) {
      decodedText += vocabChars_[static_cast<size_t>(bestIdx)];
      confidenceSum += std::min(bestProb, 1.0F);
      numChars++;
    }
  }
  return {
      decodedText,
      numChars > 0 ? confidenceSum / static_cast<float>(numChars) : 0.0F};
}

std::pair<std::string, float>
StepDoctrRecognitionGGML::decodeCTC(const cv::Mat& preds, int batchIdx) {
  const int seqLen = preds.size[1];
  const int vocabSize = preds.size[2];
  std::string decodedText;
  float minConfidence = 1.0F;
  int prevIdx = -1;

  for (int t = 0; t < seqLen; t++) {
    auto [bestIdx, bestProb] = softmaxArgmax(preds, batchIdx, t, vocabSize);
    minConfidence = std::min(minConfidence, bestProb);
    if (bestIdx >= SPECIAL_TOKEN_IDX) {
      prevIdx = -1;
      continue;
    }
    if (bestIdx == prevIdx) {
      continue;
    }
    if (bestIdx >= 0 && std::cmp_less(bestIdx, vocabChars_.size())) {
      decodedText += vocabChars_[static_cast<size_t>(bestIdx)];
    }
    prevIdx = bestIdx;
  }
  return {decodedText, decodedText.empty() ? 0.0F : minConfidence};
}

StepDoctrRecognitionGGML::Output StepDoctrRecognitionGGML::process(
    Input input, const std::atomic<bool>* cancelFlag) {
  QLOG(
      qvac_lib_inference_addon_cpp::logger::Priority::DEBUG,
      "[DoctrRecognitionGGML] Processing " +
          std::to_string(input.polygons.size()) + " text regions");

  const cv::Mat& origImg = input.context.origImg;
  Output results;
  results.reserve(input.polygons.size());

  for (size_t batchStart = 0; batchStart < input.polygons.size();
       batchStart += static_cast<size_t>(batchSize_)) {
    if (cancelFlag != nullptr && cancelFlag->load(std::memory_order_relaxed)) {
      QLOG(
          qvac_lib_inference_addon_cpp::logger::Priority::INFO,
          "[DoctrRecognitionGGML] Cancelled at batch offset " +
              std::to_string(batchStart));
      break;
    }

    const size_t batchEnd = std::min(
        batchStart + static_cast<size_t>(batchSize_), input.polygons.size());
    for (size_t i = batchStart; i < batchEnd; ++i) {
      cv::Mat crop = preprocessCrop(origImg, input.polygons[i]);
      cv::Mat preds = runSingleInference(crop);
      auto [text, confidence] = (decodingMethod_ == DecodingMethod::CTC)
                                    ? decodeCTC(preds, 0)
                                    : decodeAttention(preds, 0);

      std::array<cv::Point2f, 4> polygon = input.polygons[i];
      if (input.context.initialResizeRatio != 1.0F) {
        const float scaleBack = 1.0F / input.context.initialResizeRatio;
        for (auto& pt : polygon) {
          pt.x *= scaleBack;
          pt.y *= scaleBack;
        }
      }
      results.emplace_back(polygon, text, confidence);
    }
  }

  QLOG(
      qvac_lib_inference_addon_cpp::logger::Priority::INFO,
      "[DoctrRecognitionGGML] Completed recognition of " +
          std::to_string(results.size()) + " regions");
  return results;
}

} // namespace doctr::ggml::pipeline

// NOLINTEND(cppcoreguidelines-pro-bounds-pointer-arithmetic,cppcoreguidelines-pro-bounds-constant-array-index,readability-identifier-naming,readability-identifier-length)
