// THIS FILE IS AUTO-GENERATED BY models/update-models
// DO NOT MODIFY MANUALLY
//
// PLACEHOLDER: ships empty so the package typechecks and publishes before
// the codegen task (QVAC-19194 workstream 2) lands. Once
// `bun run update-models` runs against the production P2P registry, this
// file is overwritten with one `ModelConstant<TEndpoint>` per catalog entry
// (e.g. `export const QWEN3_4B_INST_Q4_K_M: ModelConstant<'chat'> = { ... }`)
// plus the `allModels` array. See models/update-models/README.md for the
// regeneration workflow.

import type { ModelConstant } from './types.js'

export const allModels: ReadonlyArray<ModelConstant> = []
