import { getEndpointCategoryFromAddon, type EndpointCategory } from './schemas.ts'
import { generateExportName } from './naming.ts'
import type { ProcessedModel } from './types.ts'

export function generateModelsFileContent (models: ProcessedModel[]): string {
  const usedNames = new Set<string>()
  const named = new Map<ProcessedModel, string>()

  const exportable = models.filter((m) => !m.isCompanionOnly)
  const companionOnly = models.filter((m) => m.isCompanionOnly)

  for (const m of exportable) {
    named.set(m, assignName(m, usedNames))
  }
  for (const m of companionOnly) {
    named.set(m, assignName(m, usedNames))
  }

  // Derive endpointCategory for every model. Models whose addon has no
  // OpenAI-shaped endpoint (currently `vad` and `other`) are excluded from
  // the generated file so consumers can't accidentally pass them to a chat
  // / embedding / transcription / etc. factory. They still exist in the
  // P2P registry and remain reachable via the SDK directly.
  const withCategory: (ProcessedModel & { name: string; endpointCategory: EndpointCategory })[] = []
  const dropped: { name: string; addon: string }[] = []
  for (const m of models) {
    const name = named.get(m)!
    const endpointCategory = getEndpointCategoryFromAddon(m.addon)
    if (endpointCategory === null) {
      dropped.push({ name, addon: m.addon })
      continue
    }
    withCategory.push({ ...m, name, endpointCategory })
  }

  if (dropped.length > 0) {
    console.log(`\n⏭️  Skipped ${dropped.length} model(s) with no OpenAI-shaped endpoint:`)
    for (const d of dropped.slice(0, 10)) {
      console.log(`  - ${d.name} (addon=${d.addon})`)
    }
    if (dropped.length > 10) {
      console.log(`  ... and ${dropped.length - 10} more`)
    }
  }

  return generateFileContentWithNames(withCategory)
}

function assignName (m: ProcessedModel, usedNames: Set<string>): string {
  return generateExportName({
    path: m.registryPath,
    engine: m.engine,
    name: m.modelName,
    quantization: m.quantization,
    params: m.params,
    tags: m.tags,
    usedNames
  })
}

function generateFileContentWithNames (
  modelsWithNames: (ProcessedModel & { name: string; endpointCategory: EndpointCategory })[]
): string {
  const entries = modelsWithNames
    .map((m) => {
      let entry = `  {
    name: "${m.name}",
    src: \`registry://${m.registrySource}/${m.registryPath}\`,
    registryPath: "${m.registryPath}",
    registrySource: "${m.registrySource}",
    blobCoreKey: "${m.blobCoreKey}",
    blobBlockOffset: ${m.blobBlockOffset},
    blobBlockLength: ${m.blobBlockLength},
    blobByteOffset: ${m.blobByteOffset},
    modelId: "${m.modelId}",
    addon: "${m.addon}",
    expectedSize: ${m.expectedSize},
    sha256Checksum: "${m.sha256Checksum}",
    engine: "${m.engine}",
    quantization: "${m.quantization || ''}",
    params: "${m.params || ''}",
    endpointCategory: "${m.endpointCategory}"`

      if (m.shardMetadata) {
        entry += `,\n    shardMetadata: ${JSON.stringify(m.shardMetadata)}`
      }

      if (m.companionSet) {
        entry += `,\n    companionSet: ${JSON.stringify(m.companionSet)}`
      }

      entry += '\n  } as const'
      return entry
    })
    .join(',\n')

  const exports = modelsWithNames
    .filter((m) => !m.isCompanionOnly)
    .map((m) => {
      const i = modelsWithNames.indexOf(m)
      return `export const ${m.name}: ModelConstant<"${m.endpointCategory}"> = allModels[${i}];`
    })
    .join('\n')

  return `// THIS FILE IS AUTO-GENERATED BY models/update-models
// DO NOT MODIFY MANUALLY
//
// Run \`bun run update-models\` from the package root to regenerate.

import type { ModelConstant } from './types.js'

export const allModels = [
${entries}
] as const

${exports}
`
}
