/**
 * Section-scoped version manifest. Only the API summary and the release
 * notes are versioned in the docs site — everything else (about-qvac,
 * getting-started, examples, tutorials, addons, cli, http-server) lives at
 * a single bare path that always reflects the current SDK.
 *
 * Each section is a single content folder under `content/docs/<basePath>/`:
 *   - The latest version is served from `index.mdx` at the bare basePath.
 *   - Older versions are served from `<basePath>/v<X.Y.Z>` via a sibling
 *     MDX file (`v<X.Y.Z>.mdx`).
 *
 * Auto-generated by `scripts/update-versions-list.ts` — do not edit by
 * hand for routine releases.
 */

export interface VersionEntry {
  label: string;
  value: string;
  isLatest?: boolean;
}

export interface VersionedSection {
  basePath: string;
  latest: string;
  versions: VersionEntry[];
}

export const API_SECTION: VersionedSection = {
  basePath: '/sdk/api',
  latest: 'v0.10.0',
  versions: [
    { label: 'v0.10.0 (latest)', value: 'v0.10.0', isLatest: true },
    { label: 'v0.9.1', value: 'v0.9.1' },
    { label: 'v0.8.0', value: 'v0.8.0' },
    { label: 'v0.7.0', value: 'v0.7.0' },
  ],
};

export const RELEASE_NOTES_SECTION: VersionedSection = {
  basePath: '/sdk/release-notes',
  latest: 'v0.10.0',
  versions: [
    { label: 'v0.10.0 (latest)', value: 'v0.10.0', isLatest: true },
    { label: 'v0.9.1', value: 'v0.9.1' },
    { label: 'v0.8.0', value: 'v0.8.0' },
    { label: 'v0.7.0', value: 'v0.7.0' },
  ],
};

const VERSIONED_SECTIONS: VersionedSection[] = [
  API_SECTION,
  RELEASE_NOTES_SECTION,
];

/**
 * Re-exported for backward compatibility with consumers that advertise the
 * latest SDK version in plain text (e.g. the `llms.txt` route).
 */
export const LATEST_VERSION = API_SECTION.latest;

/**
 * Return the versioned section the given pathname falls under, or `null`
 * when the pathname is not within any versioned section.
 */
export function getVersionedSection(
  pathname: string,
): VersionedSection | null {
  const normalized = pathname.replace(/\/+$/, '') || '/';
  return (
    VERSIONED_SECTIONS.find(
      (section) =>
        normalized === section.basePath ||
        normalized.startsWith(section.basePath + '/'),
    ) ?? null
  );
}

/**
 * Extract the current version slug from a versioned-section pathname.
 * Returns `section.latest` when on the bare `basePath` (`index.mdx`).
 */
export function getCurrentVersion(
  pathname: string,
  section: VersionedSection,
): string {
  const tail = pathname
    .slice(section.basePath.length)
    .replace(/^\/+|\/+$/g, '');
  if (!tail) return section.latest;
  return tail.split('/')[0];
}

/**
 * Build the URL to navigate to when the user picks a target version inside
 * a section. The latest version maps to the bare `basePath`; any other
 * version maps to `basePath/<value>`.
 */
export function computeSectionVersionUrl(
  section: VersionedSection,
  targetVersion: string,
): string {
  if (targetVersion === section.latest) return section.basePath;
  return `${section.basePath}/${targetVersion}`;
}
