import { promises as fsp } from "node:fs";
import {
  buildNestedPathIndex,
  extractBarePackHeader,
  extractPackedString,
} from "@/commands/bundle/manifest";
import {
  deduplicateAddons,
  readAddonPackageJson,
  type CollectDiagnostics,
  type NativeAddon,
} from "@/commands/verify/addon-source";

export class InvalidBundleSourceError extends Error {
  bundlePath: string;
  constructor(bundlePath: string, cause: unknown) {
    const reason = cause instanceof Error ? cause.message : String(cause);
    super(
      `Bundle at ${bundlePath} could not be parsed as a bare-pack bundle.\n\n` +
        `  Reason: ${reason}\n\n` +
        "  Make sure the path points to a worker.bundle.js generated by bundleSdk.",
    );
    this.name = "InvalidBundleSourceError";
    this.bundlePath = bundlePath;
  }
}

export interface CollectAddonsFromBundleOptions {
  bundlePath: string;
  projectRoot: string;
  diagnostics?: CollectDiagnostics;
}

export async function collectAddonsFromBundle(
  options: CollectAddonsFromBundleOptions,
): Promise<NativeAddon[]> {
  const { bundlePath, projectRoot, diagnostics } = options;

  let bundleText: string;
  try {
    bundleText = await fsp.readFile(bundlePath, "utf8");
  } catch (error) {
    throw new InvalidBundleSourceError(bundlePath, error);
  }

  let resolutions: Record<string, unknown>;
  try {
    const packed = extractPackedString(bundleText);
    const header = extractBarePackHeader(packed);
    resolutions = header.resolutions ?? {};
  } catch (error) {
    throw new InvalidBundleSourceError(bundlePath, error);
  }

  if (diagnostics !== undefined && Object.keys(resolutions).length === 0) {
    diagnostics.emptyResolutions = true;
  }

  const pathsByPackage = buildNestedPathIndex(resolutions, projectRoot);

  const addons: NativeAddon[] = [];
  for (const [pkgName, candidates] of pathsByPackage) {
    for (const candidate of candidates) {
      const result = await readAddonPackageJson({
        packageJsonPath: candidate,
        expectedName: pkgName,
      });
      if (result.isAddon && result.addon) {
        addons.push(result.addon);
      } else if (result.invalid !== undefined && diagnostics !== undefined) {
        diagnostics.invalidPackageJsons.push(result.invalid);
      }
    }
  }

  return deduplicateAddons(addons);
}
