# Build-only workflow. Publishing is handled by on-merge-qvac-lib-infer-onnx-tts.yml
name: Prebuilds (TTS)

on:
  workflow_dispatch:
    inputs:
      workdir:
        description: "Working directory inside the repo (monorepo package path)"
        required: false
        default: "packages/qvac-lib-infer-onnx-tts"
        type: string

  workflow_call:
    inputs:
      ref:
        description: "ref"
        type: string
        required: false
      repository:
        type: string
        required: false
        default: "tetherto/qvac"
      workdir:
        description: "Working directory inside the repo (monorepo package path)"
        type: string
        required: false
        default: "packages/qvac-lib-infer-onnx-tts"

permissions:
  contents: read

jobs:
  prebuild:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    uses: ./.github/workflows/reusable-prebuilds.yml
    with:
      workdir: ${{ inputs.workdir }}
      ref: ${{ inputs.ref }}
      repository: ${{ inputs.repository }}
      artifact-name-prefix: onnx-tts-
      setup-python-on-windows: true
      setup-rust-toolchain: true
    secrets: inherit
