# Build-only workflow. Publishing is handled by on-merge-qvac-lib-infer-onnx.yml
name: "Prebuilds (ONNX)"

on:
  workflow_dispatch:
    inputs:
      workdir:
        description: "Working directory (optional)"
        required: false
        type: string
        default: "packages/qvac-lib-infer-onnx"

  workflow_call:
    inputs:
      ref:
        description: "ref"
        type: string
        required: false
      repository:
        type: string
        required: false
        # monorepo default
        default: "tetherto/qvac"
      workdir:
        description: "Working directory (optional)"
        required: false
        type: string
        default: "packages/qvac-lib-infer-onnx"

permissions:
  contents: read

jobs:
  prebuild:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    uses: ./.github/workflows/reusable-prebuilds.yml
    with:
      workdir: ${{ inputs.workdir }}
      ref: ${{ inputs.ref }}
      repository: ${{ inputs.repository }}
      artifact-name-prefix: onnx-
    secrets: inherit
