// This file is autogenerated by the hyperdispatch compiler
/* eslint-disable camelcase */

const { c, b4a, assert, DispatchError, ERRORS } = require('hyperdispatch/runtime')
const { version, getEncoding, setVersion } = require('./messages.js')

const defaultVersion = version

class Router {
  constructor () {
    this._handler0 = null
    this._handler1 = null
    this._handler2 = null
    this._handler3 = null
    this._handler4 = null

    this._missing = 5
  }

  add (name, handler) {
    switch (name) {
      case '@qvac-main-registry/put-model':
        this._handler0 = handler
        break
      case '@qvac-main-registry/put-license':
        this._handler1 = handler
        break
      case '@qvac-main-registry/add-indexer':
        this._handler2 = handler
        break
      case '@qvac-main-registry/remove-indexer':
        this._handler3 = handler
        break
      case '@qvac-main-registry/delete-model':
        this._handler4 = handler
        break
      default:
        throw DispatchError.NONEXISTENT_ROUTE(name)
    }
    this._missing--
  }

  _checkAll () {
    assert(this._handler0 !== null, 'Missing handler for "@qvac-main-registry/put-model"')
    assert(this._handler1 !== null, 'Missing handler for "@qvac-main-registry/put-license"')
    assert(this._handler2 !== null, 'Missing handler for "@qvac-main-registry/add-indexer"')
    assert(this._handler3 !== null, 'Missing handler for "@qvac-main-registry/remove-indexer"')
    assert(this._handler4 !== null, 'Missing handler for "@qvac-main-registry/delete-model"')
  }

  async dispatch (message, context) {
    if (this._missing > 0) {
      this._checkAll()
    }

    setVersion(defaultVersion)

    const op = b4a.isBuffer(message) ? decode(message) : message

    switch (op.id) {
      case 0:
        return this._handler0(op.value, context)
      case 1:
        return this._handler1(op.value, context)
      case 2:
        return this._handler2(op.value, context)
      case 3:
        return this._handler3(op.value, context)
      case 4:
        return this._handler4(op.value, context)
      default:
        throw DispatchError.HANDLER_NOT_FOUND_BY_ID(op.id)
    }
  }
}

function encode (name, message, { version = defaultVersion } = {}) {
  const state = { buffer: null, start: 0, end: 0 }

  const route = getRouteByName(name)
  setVersion(version)

  c.uint.preencode(state, route.id)
  route.enc.preencode(state, message)

  state.buffer = b4a.allocUnsafe(state.end)
  c.uint.encode(state, route.id)
  route.enc.encode(state, message)

  return state.buffer
}

function decode (buffer, { version = defaultVersion } = {}) {
  const state = { buffer, start: 0, end: buffer.length }

  const id = c.uint.decode(state)
  const route = getRouteById(id)
  setVersion(version)

  const value = route.enc.decode(state)
  return { id, name: route.name, value }
}

const route0 = {
  name: '@qvac-main-registry/put-model',
  id: 0,
  enc: getEncoding('@qvac-main-registry/model')
}

const route1 = {
  name: '@qvac-main-registry/put-license',
  id: 1,
  enc: getEncoding('@qvac-main-registry/license')
}

const route2 = {
  name: '@qvac-main-registry/add-indexer',
  id: 2,
  enc: getEncoding('@qvac-main-registry/writer')
}

const route3 = {
  name: '@qvac-main-registry/remove-indexer',
  id: 3,
  enc: getEncoding('@qvac-main-registry/writer')
}

const route4 = {
  name: '@qvac-main-registry/delete-model',
  id: 4,
  enc: getEncoding('@qvac-main-registry/model-key')
}

function getRouteByName (name) {
  switch (name) {
    case '@qvac-main-registry/put-model':
      return route0
    case '@qvac-main-registry/put-license':
      return route1
    case '@qvac-main-registry/add-indexer':
      return route2
    case '@qvac-main-registry/remove-indexer':
      return route3
    case '@qvac-main-registry/delete-model':
      return route4
    default:
      throw DispatchError.ROUTE_NOT_FOUND_BY_NAME(name)
  }
}

function getRouteById (id) {
  switch (id) {
    case 0:
      return route0
    case 1:
      return route1
    case 2:
      return route2
    case 3:
      return route3
    case 4:
      return route4
    default:
      throw DispatchError.HANDLER_NOT_FOUND_BY_ID(id)
  }
}

module.exports = {
  version,
  encode,
  decode,
  Router,
  DispatchError,
  ERRORS
}
